const projects = {"grades": {"title": "Grade Dashboard", "role": "Team leader · 6-person team", "description": "An interactive Java dashboard for exploring student grades and predicting subject outcomes, combining data visualisation with a custom tree-based model.", "tags": ["Java", "JavaFX", "Machine learning"], "images": [["grades-charts", "Grade distribution dashboard"], ["grades-prediction", "Grade prediction and evaluation"]], "detail": "I led a six-person team on this completed project. The application combines interactive grade analysis with subject predictions and holdout evaluation."}, "putting": {"title": "Crazy Putting", "role": "Team member · 6-person team", "description": "A golf simulator combining numerical physics with automated shot selection, exploring rule-based strategies, hill climbing, and regression-based optimisation.", "tags": ["Java", "Simulation", "Optimisation"], "images": [["putting-course", "Golf simulation and automated shot selection"], ["putting-time", "ODE solver time plot"], ["putting-phase", "ODE solver phase-space plot"], ["putting-setup", "Course setup"]], "detail": "I contributed as a member of a six-person team. This completed project includes numerical solvers, configurable courses, and automated shot-selection strategies."}, "treasurer": {"title": "Treasurer", "role": "Solo project", "description": "A desktop finance workspace for student associations, bringing together local receipt recognition, transaction management, and portable backups. Built as a productivity tool for my Treasurer position at MSV Incognito.", "tags": ["React", "Tauri", "Local OCR"], "images": [["treasurer-receipts", "Receipt library"], ["treasurer-settings", "Categories and financial periods"], ["treasurer-transaction", "Transaction entry"], ["treasurer-home", "Financial overview"]], "detail": "I built this completed application independently to support my responsibilities as Treasurer of MSV Incognito."}, "befit": {"title": "BeFit", "role": "Solo project", "description": "An iOS weight-tracking app with offline storage, progress visualisation, and optional iCloud synchronisation.", "tags": ["SwiftUI", "SwiftData", "CloudKit"], "images": [["befit-home", "BeFit home dashboard"], ["befit-graph", "Weight trends and history"]], "detail": "I built this completed iOS application independently, including its local storage, progress views, and synchronisation workflow."}};

const dialog=document.querySelector('#details');
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{
 const project=projects[button.dataset.project];
 document.querySelector('#dialog-type').textContent='Completed · '+project.role;
 document.querySelector('#dialog-title').textContent=project.title;
 const content=document.querySelector('#dialog-content');content.replaceChildren();
 [project.description,project.detail].forEach(text=>{const p=document.createElement('p');p.textContent=text;content.append(p)});
 project.images.forEach(([file,caption])=>{const figure=document.createElement('figure');const link=document.createElement('a');link.href='assets/projects/'+file+'.png';link.target='_blank';link.rel='noopener';link.setAttribute('aria-label','Open full-size screenshot: '+caption);const img=document.createElement('img');img.src=link.href;img.alt=caption;img.loading='lazy';link.append(img);const label=document.createElement('figcaption');label.textContent=caption;figure.append(link,label);content.append(figure)});
 dialog.showModal();dialog.scrollTop=0;
}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
const track=document.querySelector('#project-cards');
const prev=document.querySelector('#projects-prev'),next=document.querySelector('#projects-next');
function updateArrows(){prev.disabled=track.scrollLeft<2;next.disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-2}
function move(direction){track.scrollBy({left:direction*(track.querySelector('.card').getBoundingClientRect().width+20),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));
track.addEventListener('keydown',e=>{if(e.target!==track)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}});
track.addEventListener('scroll',updateArrows);window.addEventListener('resize',updateArrows);updateArrows();
